FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY ./processor/build/libs/processor.jar app.jar

EXPOSE 8082

ENV JAVA_OPTS="-Xms512m -Xmx1g -XX:+UseG1GC"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]