global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'waf-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'gateway'

  - job_name: 'alert-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          service: 'alert'

  - job_name: 'stream-processor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          service: 'processor'