apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    url: http://clickhouse:9000
    user: default
    database: security
    isDefault: false
    editable: true
    jsonData:
      port: 9000
      database: security
      defaultDatabase: security
      username: default
      tlsSkipVerify: true
